name: Build and deploy to prod env

on:
  push:
    branches: [master]

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Build Backend
        run: |
          sudo npm i -g pm2
          sudo npm cache verify
          sudo npm install
          sudo npm run build:prod
      - name: zip dist folder
        run: tar -czvf dist.tar.gz dist

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VM_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.VM_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: git pull and npm install
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME}}@${{ secrets.VM_KNOWN_HOSTS }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "cd ${{ secrets.TARGET_PATH }};git pull;source ~/.nvm/nvm.sh;npm install --force;"
      - name: scp to ec2instance
        run: |
          scp dist.tar.gz ${{ secrets.VM_USERNAME}}@${{ secrets.VM_KNOWN_HOSTS }}:${{ secrets.TARGET_PATH }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "cd ${{ secrets.TARGET_PATH }};tar -xzvf dist.tar.gz; rm dist.tar.gz;export PATH=$PATH:'/home/ubuntu/.nvm/versions/node/v16.18.0/bin'; source ~/.bashrc;npm run prisma:generate:prod; pm2 restart 0;"